/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({
  'school' : IDL.Null,
  'college' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : Category,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const InquirySubmission = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'message' : IDL.Text,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});
export const InquiryResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'submitInquiry' : IDL.Func([InquirySubmission], [InquiryResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({ 'school' : IDL.Null, 'college' : IDL.Null });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : Category,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const InquirySubmission = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'message' : IDL.Text,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const InquiryResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func([InquirySubmission], [InquiryResult], []),
  });
};

export const init = ({ IDL }) => { return []; };