/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'school' : null } |
  { 'college' : null };
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'size' : string,
  'productId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
  'phone' : string,
}
export type InquiryResult = { 'ok' : bigint } |
  { 'err' : string };
export interface InquirySubmission {
  'name' : string,
  'color' : string,
  'size' : string,
  'productId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'quantity' : bigint,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : Category,
  'colors' : Array<string>,
  'price' : bigint,
}
export interface _SERVICE {
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'submitInquiry' : ActorMethod<[InquirySubmission], InquiryResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];